# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteRunRecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteRunWindow(object):
    def setupUi(self, DeleteRunWindow):
        DeleteRunWindow.setObjectName("DeleteRunWindow")
        DeleteRunWindow.resize(600, 350)
        self.label = QtWidgets.QLabel(DeleteRunWindow)
        self.label.setGeometry(QtCore.QRect(30, 40, 291, 51))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(DeleteRunWindow)
        self.textEdit.setGeometry(QtCore.QRect(30, 80, 521, 161))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.confirm_pushButton = QtWidgets.QPushButton(DeleteRunWindow)
        self.confirm_pushButton.setGeometry(QtCore.QRect(490, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.confirm_pushButton.setFont(font)
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(DeleteRunWindow)
        self.cancel_pushButton.setGeometry(QtCore.QRect(410, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cancel_pushButton.setFont(font)
        self.cancel_pushButton.setObjectName("cancel_pushButton")

        self.retranslateUi(DeleteRunWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteRunWindow)

    def retranslateUi(self, DeleteRunWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteRunWindow.setWindowTitle(_translate("DeleteRunWindow", "Dialog"))
        self.label.setText(_translate("DeleteRunWindow", "Are you sure you\'d like to delete this run?"))
        self.textEdit.setHtml(_translate("DeleteRunWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bitstream Charter\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt;\">Note: Performing this action will remove the entire run record. You will no longer be able to access this information again.</span></p></body></html>"))
        self.confirm_pushButton.setText(_translate("DeleteRunWindow", "Confirm"))
        self.cancel_pushButton.setText(_translate("DeleteRunWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteRunWindow = QtWidgets.QDialog()
    ui = Ui_DeleteRunWindow()
    ui.setupUi(DeleteRunWindow)
    DeleteRunWindow.show()
    sys.exit(app.exec_())
