# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './EditScanTypes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditScanTypes(object):
    def setupUi(self, EditScanTypes):
        EditScanTypes.setObjectName("EditScanTypes")
        EditScanTypes.resize(480, 460)
        self.scanType_add_pushButton = QtWidgets.QPushButton(EditScanTypes)
        self.scanType_add_pushButton.setGeometry(QtCore.QRect(390, 150, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.scanType_add_pushButton.setFont(font)
        self.scanType_add_pushButton.setStyleSheet("")
        self.scanType_add_pushButton.setObjectName("scanType_add_pushButton")
        self.configuration_or_label = QtWidgets.QLabel(EditScanTypes)
        self.configuration_or_label.setGeometry(QtCore.QRect(10, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.configuration_or_label.setFont(font)
        self.configuration_or_label.setObjectName("configuration_or_label")
        self.textEdit = QtWidgets.QTextEdit(EditScanTypes)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.cancelScanType_pushButton = QtWidgets.QPushButton(EditScanTypes)
        self.cancelScanType_pushButton.setGeometry(QtCore.QRect(380, 400, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.cancelScanType_pushButton.setFont(font)
        self.cancelScanType_pushButton.setStyleSheet("background-color: rgb(206, 0, 0);")
        self.cancelScanType_pushButton.setObjectName("cancelScanType_pushButton")
        self.saveScanType_pushButton = QtWidgets.QPushButton(EditScanTypes)
        self.saveScanType_pushButton.setEnabled(False)
        self.saveScanType_pushButton.setGeometry(QtCore.QRect(380, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.saveScanType_pushButton.setFont(font)
        self.saveScanType_pushButton.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.saveScanType_pushButton.setObjectName("saveScanType_pushButton")
        self.scanType_remove_pushButton = QtWidgets.QPushButton(EditScanTypes)
        self.scanType_remove_pushButton.setEnabled(False)
        self.scanType_remove_pushButton.setGeometry(QtCore.QRect(390, 190, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.scanType_remove_pushButton.setFont(font)
        self.scanType_remove_pushButton.setStyleSheet("background-color: rgb(206, 0, 0);")
        self.scanType_remove_pushButton.setObjectName("scanType_remove_pushButton")
        self.scanType_groupBox = QtWidgets.QGroupBox(EditScanTypes)
        self.scanType_groupBox.setGeometry(QtCore.QRect(10, 120, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.scanType_groupBox.setFont(font)
        self.scanType_groupBox.setObjectName("scanType_groupBox")
        self.scanType_comboBox = QtWidgets.QComboBox(self.scanType_groupBox)
        self.scanType_comboBox.setGeometry(QtCore.QRect(10, 31, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scanType_comboBox.setFont(font)
        self.scanType_comboBox.setObjectName("scanType_comboBox")
        self.tableWidget = QtWidgets.QTableWidget(EditScanTypes)
        self.tableWidget.setGeometry(QtCore.QRect(10, 190, 361, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(EditScanTypes)
        QtCore.QMetaObject.connectSlotsByName(EditScanTypes)

    def retranslateUi(self, EditScanTypes):
        _translate = QtCore.QCoreApplication.translate
        EditScanTypes.setWindowTitle(_translate("EditScanTypes", "Edit Scan Types"))
        self.scanType_add_pushButton.setText(_translate("EditScanTypes", "+ Add"))
        self.configuration_or_label.setText(_translate("EditScanTypes", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Edit Scan Types</span></p></body></html>"))
        self.textEdit.setHtml(_translate("EditScanTypes", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bitstream Charter\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please indicate which scan(s) would you like to perform with this Run.</p></body></html>"))
        self.cancelScanType_pushButton.setText(_translate("EditScanTypes", "Cancel"))
        self.saveScanType_pushButton.setText(_translate("EditScanTypes", "Save"))
        self.scanType_remove_pushButton.setText(_translate("EditScanTypes", "Remove"))
        self.scanType_groupBox.setTitle(_translate("EditScanTypes", "Scan Type"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EditScanTypes", "Added Scan Types"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditScanTypes = QtWidgets.QDialog()
    ui = Ui_EditScanTypes()
    ui.setupUi(EditScanTypes)
    EditScanTypes.show()
    sys.exit(app.exec_())
